name: webcam_emulator
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - opencv
  - h5py
  - ujson
  - tqdm
  - loguru
  - flake8
  - black
  - ipython
  - pytest
  - pip
  - pip:
      - tk
